# Project information
site_name: My Machines Documentation Portal
site_url: "https://docs.my-machines.com"
site_author: "Edgar Mata"
site_description: "My Machines knowledge base"

# Repository global
repo_name: "EdgarMata/my-machines-docs"
repo_url: "https://github.com/EdgarMata/my-machines-docs"
edit_uri: edit/main/docs/

# Copyright dinâmico
copyright: '&copy; 2022 - <span id="current-year"></span> <a href="https://my-machines.net/" target="_blank" rel="noopener">My Machines</a> by Edgar Mata'

# Configuration
theme:
  name: 'material'
  language: 'en' # Mantém em inglês global para a comunidade mundial
  logo: assets/mylogo.svg
  favicon: images/f-icon.png
  custom_dir: overrides
  features:
    - navigation.tabs          # Menu superior horizontal por famílias de máquinas
    - navigation.sections      # Agrupa os submenus na barra lateral de forma limpa
    - navigation.expand        # Mantém as secções expansíveis na lateral
    - navigation.top           # Botão "Voltar ao topo" automático
    - navigation.path
    - navigation.footer
    - toc.follow
    - search.suggest           # Sugestões automáticas na pesquisa
    - search.highlight         # Destaca o texto pesquisado
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - header.autohide

  palette:
    # Ajuste automático pelo sistema operacional
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: System Preferences

    # Modo Claro (Light Mode)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: indigo

    # Modo Escuro (Dark Mode)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode
      primary: light blue
      accent: indigo

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/EdgarMata
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/machines.net/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/machines_net/
    - icon: fontawesome/brands/pinterest
      link: https://pt.pinterest.com/machines_net
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@machines_net
    - icon: fontawesome/solid/paper-plane
      link: mailto:geral@my-machines.net
  analytics:
    provider: google
    property: G-B2Y6R89EJ9
    feedback:
      title: Did this page help?
      ratings:
        - icon: material/thumb-up-outline
          name: Did this page help
          data: 1
          note: >-
            Thanks for the feedback!
        - icon: material/thumb-down-outline
          name: This page can be improved
          data: 0
          note: >-
            Thanks for the feedback! Help us improve this page
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSf_kuzfD_Tbez4b-jqxr0dPAsu4QGP72imTuG0AKUAi-gQKLg/viewform?usp=pp_url&entry.756152555={url}" target="_blank" rel="noopener">feedback form</a>.

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
  - assets/extra.css

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - toc:
      permalink: true
      title: Table of Contents

# ARQUITETURA MULTI-MÁQUINA INTEGRADA
nav:
  - Home: index.md

  - '3D Printers':
      - 'MY-Cloner':
          - Home: '3d-printers/my-cloner/index.md'
          - Manual:
              - Overview: '3d-printers/my-cloner/manual/index.md'
              - Bill of Materials:
                  - Mechanical Parts: '3d-printers/my-cloner/manual/bom/mecanical-parts.md'
                  - Electronic Parts: '3d-printers/my-cloner/manual/bom/eletronic-parts.md'
                  - Printed Parts: '3d-printers/my-cloner/manual/bom/printed-parts.md'
              - Assembly Guide:
                  - Introduction: '3d-printers/my-cloner/manual/assembly-guide/01_introduction.md'
                  - Y-Axis Assembly: '3d-printers/my-cloner/manual/assembly-guide/02_y-axis_assembly.md'
                  - X-Axis Assembly: '3d-printers/my-cloner/manual/assembly-guide/03_x-axis_assembly.md'
                  - Z-Axis Assembly: '3d-printers/my-cloner/manual/assembly-guide/04_z-axis_assembly.md'
                  - E-Axis Assembly: '3d-printers/my-cloner/manual/assembly-guide/05_e-axis_assembly.md'
                  - LCD Assembly: '3d-printers/my-cloner/manual/assembly-guide/06_lcd_assembly.md'
                  - Heatbed and PSU Assembly: '3d-printers/my-cloner/manual/assembly-guide/07_heatbed_and_psu_assembly.md'
                  - Electronics Assembly: '3d-printers/my-cloner/manual/assembly-guide/08_electronics_assembly.md'
                  - Pre-flight Check: '3d-printers/my-cloner/manual/assembly-guide/09_pre-flight_check.md'
              - Wiring Diagram:
                  - Power Supply: '3d-printers/my-cloner/manual/wiring-diagram/power-supply.md'
                  - Mainboard: '3d-printers/my-cloner/manual/wiring-diagram/mainboard.md'
                  - Display: '3d-printers/my-cloner/manual/wiring-diagram/display.md'
                  - Motors: '3d-printers/my-cloner/manual/wiring-diagram/motors.md'
                  - Extruder: '3d-printers/my-cloner/manual/wiring-diagram/extruder.md'
                  - Endstops: '3d-printers/my-cloner/manual/wiring-diagram/endstops.md'
                  - Fans: '3d-printers/my-cloner/manual/wiring-diagram/fans.md'
              - Initial Setup:
                  - Printer Overview: '3d-printers/my-cloner/manual/inicial-setup/printer-overview.md'
                  - First Time Setup: '3d-printers/my-cloner/manual/inicial-setup/first-time-setup.md'
                  - Klipper Interface Guide: '3d-printers/my-cloner/manual/inicial-setup/klipper-interface-guide.md'
                  - Loading Filament: '3d-printers/my-cloner/manual/inicial-setup/loading-unloading-filament.md'
                  - Glossary: '3d-printers/my-cloner/manual/inicial-setup/glossary-of-terms.md'
          - Slicer:
              - Overview: '3d-printers/my-cloner/slicer/index.md'
              - Intro to Slicing: '3d-printers/my-cloner/slicer/introduction-to-slicing.md'
              - Orca Slicer: '3d-printers/my-cloner/slicer/setting-up-orca-slicer.md'
              - Prusa & Super Slicer: '3d-printers/my-cloner/slicer/prusa_and_super_slicer.md'
              - Workflow: '3d-printers/my-cloner/slicer/basic-slicing-workflow.md'
              - Print Settings: '3d-printers/my-cloner/slicer/understanding-print-settings.md'
          - Maintenance:
              - Overview: '3d-printers/my-cloner/maintenance/index.md'
              - Preventive:
                  - Belt Tension: '3d-printers/my-cloner/maintenance/preventive-maintenance/belt-tension.md'
                  - Extruder: '3d-printers/my-cloner/maintenance/preventive-maintenance/cleaning-extruder.md'
                  - Nozzle: '3d-printers/my-cloner/maintenance/preventive-maintenance/cleaning-nozzle.md'
                  - Print Bed: '3d-printers/my-cloner/maintenance/preventive-maintenance/cleaning-print-bed.md'
                  - Lubrication: '3d-printers/my-cloner/maintenance/preventive-maintenance/lubrication.md'
                  - Schedule: '3d-printers/my-cloner/maintenance/preventive-maintenance/maintenance-schedule.md'
                  - Consumables: '3d-printers/my-cloner/maintenance/preventive-maintenance/replacing-consumables.md'
              - Reactive:
                  - Fans: '3d-printers/my-cloner/maintenance/reactive-maintenance/replacing-fans.md'
                  - Heater: '3d-printers/my-cloner/maintenance/reactive-maintenance/replacing-heater.md'
                  - Hotend: '3d-printers/my-cloner/maintenance/reactive-maintenance/replacing-the-hotend.md'
                  - Nozzle Change: '3d-printers/my-cloner/maintenance/reactive-maintenance/replacing-the-nozzle.md'
                  - Thermistor: '3d-printers/my-cloner/maintenance/reactive-maintenance/replacing-thermistor.md'
          - Safety:
              - Overview: '3d-printers/my-cloner/safety/index.md'
              - Electrical: '3d-printers/my-cloner/safety/electrical-and-thermal-safety.md'
              - Chemical/Fire: '3d-printers/my-cloner/safety/chemical-and-fire-safety.md'
              - Power Supply: '3d-printers/my-cloner/safety/handling-power-supply.md'
              - Safe Usage: '3d-printers/my-cloner/safety/safe-usage.md'
          - Troubleshooting:
              - Overview: '3d-printers/my-cloner/troubleshooting/index.md'
              - Quality:
                  - Banding: '3d-printers/my-cloner/troubleshooting/banding.md'
                  - Bridging: '3d-printers/my-cloner/troubleshooting/bridging.md'
                  - Elephant Foot: '3d-printers/my-cloner/troubleshooting/elephant-foot.md'
                  - Ghosting: '3d-printers/my-cloner/troubleshooting/ghosting.md'
                  - Infill: '3d-printers/my-cloner/troubleshooting/infill-issues.md'
                  - Adhesion: '3d-printers/my-cloner/troubleshooting/layer-adhesion-issues.md'
                  - Overhangs: '3d-printers/my-cloner/troubleshooting/overhangs.md'
                  - Pillowing: '3d-printers/my-cloner/troubleshooting/pillowing.md'
                  - Stringing: '3d-printers/my-cloner/troubleshooting/stringing.md'
                  - Warping: '3d-printers/my-cloner/troubleshooting/warping.md'
              - Extrusion:
                  - Problems: '3d-printers/my-cloner/troubleshooting/extrusion-problems.md'
                  - Over-Extrusion: '3d-printers/my-cloner/troubleshooting/over-extrusion.md'
                  - Under-Extrusion: '3d-printers/my-cloner/troubleshooting/under-extrusion.md'
              - Mechanical:
                  - Hardware: '3d-printers/my-cloner/troubleshooting/hardware-issues.md'
                  - Layer Shifting: '3d-printers/my-cloner/troubleshooting/layer-shifting.md'
                  - Skipping: '3d-printers/my-cloner/troubleshooting/layers-skipping.md'
                  - Z-Axis: '3d-printers/my-cloner/troubleshooting/z-axis-issues.md'
              - Connectivity/System:
                  - Connection: '3d-printers/my-cloner/troubleshooting/connectivity-issues.md'
                  - Software: '3d-printers/my-cloner/troubleshooting/software-issues.md'
          - Tips & Tricks:
              - Overview: '3d-printers/my-cloner/tips-and-tricks/index.md'
              - Cooling: '3d-printers/my-cloner/tips-and-tricks/better-cooling.md'
              - Tuning First Layer: '3d-printers/my-cloner/tips-and-tricks/hardware-&-calibration/fine_tuning_first_layer.md'
              - Speed: '3d-printers/my-cloner/tips-and-tricks/optimized-print-speed.md'
              - Supports: '3d-printers/my-cloner/tips-and-tricks/optimized-support-settings.md'
              - Perfect Layer: '3d-printers/my-cloner/tips-and-tricks/perfect-first-layer.md'
              - Anti-Warping: '3d-printers/my-cloner/tips-and-tricks/preventing-warping.md'
              - Materials: '3d-printers/my-cloner/tips-and-tricks/printing-&-materials/tips_for_common_materials.md'
              - Vibration: '3d-printers/my-cloner/tips-and-tricks/reduce-vibration.md'
              - Stringing: '3d-printers/my-cloner/tips-and-tricks/reducing-stringing.md'
              - CAD Design: '3d-printers/my-cloner/tips-and-tricks/slicer-software/designing-for-3d-printing.md'
              - Testing: '3d-printers/my-cloner/tips-and-tricks/test-settings-with-small-prints.md'
          - Downloads:
              - Overview: '3d-printers/my-cloner/downloads/index.md'
              - STL Files: '3d-printers/my-cloner/downloads/transferencias/stl-files.md'
              - Slicer Profiles: '3d-printers/my-cloner/downloads/transferencias/slicer-profiles.md'
              - Firmware: '3d-printers/my-cloner/downloads/transferencias/firmware-configuration.md'
              - CAD Files: '3d-printers/my-cloner/downloads/transferencias/cad-files.md'
              - BOM Files: '3d-printers/my-cloner/downloads/transferencias/bom-files.md'
              - Offline Manual: '3d-printers/my-cloner/downloads/transferencias/offline-manual.md'
          - FAQ: '3d-printers/my-cloner/faq.md'
          - About:
              - Overview: '3d-printers/my-cloner/about/overview.md'
              - Features: '3d-printers/my-cloner/about/features.md'
              - Specifications: '3d-printers/my-cloner/about/specifications.md'
              - Box Contents: '3d-printers/my-cloner/about/box-contents.md'
              - Warranty: '3d-printers/my-cloner/about/warranty.md'

      - 'MY-Delta':
          - 'Overview & Safety': '3d-printers/my-delta/index.md'
          - 'Assembly Manual': '3d-printers/my-delta/assembly.md'
          - 'Software & Slicer': '3d-printers/my-delta/software.md'
          - 'Maintenance': '3d-printers/my-delta/maintenance.md'
          - 'Troubleshooting & Files': '3d-printers/my-delta/troubleshooting.md'
      - 'MY-CoreXY':
          - 'Overview & Safety': '3d-printers/my-corexy/index.md'
          - 'Assembly Manual': '3d-printers/my-corexy/assembly.md'
          - 'Software & Slicer': '3d-printers/my-corexy/software.md'
          - 'Maintenance': '3d-printers/my-corexy/maintenance.md'
          - 'Troubleshooting & Files': '3d-printers/my-corexy/troubleshooting.md'
      - 'MY-Giga1M3':
          - 'Overview & Safety': '3d-printers/my-giga1m3/index.md'
          - 'Assembly Manual': '3d-printers/my-giga1m3/assembly.md'
          - 'Software & Slicer': '3d-printers/my-giga1m3/software.md'
          - 'Maintenance': '3d-printers/my-giga1m3/maintenance.md'
          - 'Troubleshooting & Files': '3d-printers/my-giga1m3/troubleshooting.md'
      - 'MY-Mini':
          - 'Overview & Safety': '3d-printers/my-mini/index.md'
          - 'Assembly Manual': '3d-printers/my-mini/assembly.md'
          - 'Software & Slicer': '3d-printers/my-mini/software.md'
          - 'Maintenance': '3d-printers/my-mini/maintenance.md'
          - 'Troubleshooting & Files': '3d-printers/my-mini/troubleshooting.md'

  - 'Laser Cutters':
      - 'MY-CO2Laser CNC':
          - 'Overview & Safety': 'laser-cutters/my-co2-laser/index.md'
          - 'Assembly Manual': 'laser-cutters/my-co2-laser/assembly.md'
          - 'Software & Firmware': 'laser-cutters/my-co2-laser/software.md'
          - 'Maintenance': 'laser-cutters/my-co2-laser/maintenance.md'
          - 'Troubleshooting & Files': 'laser-cutters/my-co2-laser/troubleshooting.md'
      - 'MY-Laser CNC':
          - 'Overview & Safety': 'laser-cutters/my-laser/index.md'
          - 'Assembly Manual': 'laser-cutters/my-laser/assembly.md'
          - 'Software & Firmware': 'laser-cutters/my-laser/software.md'
          - 'Maintenance': 'laser-cutters/my-laser/maintenance.md'
          - 'Troubleshooting & Files': 'laser-cutters/my-laser/troubleshooting.md'

  - 'CNC Routers':
      - 'MY-Router CNC':
          - 'CNC Routers Overview': 'cnc-routers/my-router-cnc/index.md'
          - 'Assembly Manual': 'cnc-routers/my-router-cnc/assembly.md'
          - 'Software & CAM': 'cnc-routers/my-router-cnc/software.md'
          - 'Maintenance': 'cnc-routers/my-router-cnc/maintenance.md'
          - 'Troubleshooting & Files': 'cnc-routers/my-router-cnc/troubleshooting.md'
      - 'MY-RouterXL CNC':
          - 'Overview & Safety': 'cnc-routers/my-router-xl/index.md'
          - 'Assembly Manual': 'cnc-routers/my-router-xl/assembly.md'
          - 'Software & CAM': 'cnc-routers/my-router-xl/software.md'
          - 'Maintenance': 'cnc-routers/my-router-xl/maintenance.md'
          - 'Troubleshooting & Files': 'cnc-routers/my-router-xl/troubleshooting.md'
      - 'MY-PCB Mill':
          - 'Overview & Safety': 'cnc-routers/my-pcb-mill/index.md'
          - 'Assembly Manual': 'cnc-routers/my-pcb-mill/assembly.md'
          - 'Software & CAM': 'cnc-routers/my-pcb-mill/software.md'
          - 'Maintenance': 'cnc-routers/my-pcb-mill/maintenance.md'
          - 'Troubleshooting & Files': 'cnc-routers/my-pcb-mill/troubleshooting.md'