name: deploy-docs


on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar MkDocs Material
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin

      - name: Compilar Site Estatico
        run: mkdocs build

      - name: Sincronizar com Servidor Oracle
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          SERVER_IP: ${{ secrets.VPS_IP }}
          SERVER_USER: ${{ secrets.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --delete site/ $SERVER_USER@$SERVER_IP:/opt/infrastructure/mkdocs/site/