name: deploy-docs

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build MkDocs via Docker
        run: |
          docker run --rm -v $(pwd):/docs squidfunk/mkdocs-material build

      - name: Move files to Web Folder
        run: |
          mkdir -p /var/www/my-machines-docs
          cp -r site/* /var/www/my-machines-docs/